### ISSUE TITLE
Oauth token not generated despite correct login info

### ISSUE THREAD

**Issue by dmoon86** [noahc3/PokemonGoTeamManager#3]
C:\Users\Daniel\Desktop\Pokemon+GO+Team+Manager+1.3.1\libs\py\pogoapi>python pogotesting.py /wait
('Authorization Type Detected: ', 'google')
Line 83,api.py - 2016-07-28 19:45:13,194 - INFO - Creating Google session for (gmail-edited)
Line 788,connectionpool.py - 2016-07-28 19:45:13,201 - INFO - Starting new HTTPS connection (1): android.clients.google.com
Line 788,connectionpool.py - 2016-07-28 19:45:13,737 - INFO - Starting new HTTPS connection (1): android.clients.google.com
Line 78,api.py - 2016-07-28 19:45:13,835 - CRITICAL - Access token not generated
Line 284,pogotesting.py - 2016-07-28 19:45:13,836 - CRITICAL - Session not created successfully

C:\Users\Daniel\Desktop\Pokemon+GO+Team+Manager+1.3.1\libs\py\pogoapi>pause
Press any key to continue . . .

Ive added PATH and PYTHONPATH. App is just gray and wont move on.

**Comment by noahc3** [comment]
Your google login info is wrong, google authentication isn't working, or Pokemon GO servers are on fire.

**Comment by dmoon86** [comment]
ok, ive tried 3 of my google accounts and its the same. Ill let you know how it is.

**Comment by dmoon86** [comment]
Yes, still no go on the google login

**Comment by noahc3** [comment]
Alright, thanks for the info. I'll keep digging and see if i can find anything.

**Comment by noahc3** [comment]
Can you please download [1.3.2 Beta 1](https://github.com/noahc3/PokemonGoTeamManager/releases/tag/1.3.2b1) and tell me if the issue still occurs?

**Comment by dmoon86** [comment]
hey! it worked perfectly!

**Comment by noahc3** [comment]
Awesome!

**Comment by noahc3** [comment]
Fixed in [1,3,2 Beta 1](https://github.com/noahc3/PokemonGoTeamManager/releases/tag/1.3.2b1)

**Comment by noahc3** [comment]
Fixed in [1.3.2 Beta 1](https://github.com/noahc3/PokemonGoTeamManager/releases/tag/1.3.2b1)
