### ISSUE TITLE
GetPlayerResponse object is not iterable

### ISSUE THREAD

**Issue by johnpyp** [noahc3/PokemonGoTeamManager#5]
Hi,

I've been having a problem where when I try to log in, a window pops up, it lists all my pokemon and items (looks like), then at the end this happens: 
![image](https://cloud.githubusercontent.com/assets/20625636/17267483/61392d04-55d8-11e6-8aeb-f448007bbc82.png)

I used the pause to get that. After that, everything goes grey and nothing happens. Any suggestions?

**Comment by noahc3** [comment]
Can you download [1.3.2b1](https://github.com/noahc3/PokemonGoTeamManager/releases/tag/1.3.2b1) and confirm this still happens?

**Comment by johnpyp** [comment]
That is the version I am using.

**Comment by johnpyp** [comment]
Did I do something wrong for installation? I ran Required Modules, that all worked, then I ran the app, entered my info correct and it isn't working

**Comment by johnpyp** [comment]
Any other possibilities for troubleshooting?

**Comment by noahc3** [comment]
Are you using Python 2.7?

**Comment by johnpyp** [comment]
I have Python 3.5 and Python 2.7.11 installed I believe.

**Comment by noahc3** [comment]
In command line when you type python, does it return 2.7.11? If not , the problem is my program only calls python when running commands, so if it tries to run it with the 3.5 interpreter, it errors as writing to files have changed between those versions of python.

**Comment by johnpyp** [comment]
Ahhh, yes, when I ran python, it is saying 3.5.1. Should I just uninstall python 3.5.1? Or is there a better way to change it to 2.7.11?

**Comment by noahc3** [comment]
[Change your PATH](https://java.com/en/download/help/path.xml) to point to the directory of your 2.7.11 install rather than your 3.5.1 install.

**Comment by johnpyp** [comment]
Ok thank you.

**Comment by noahc3** [comment]
No, at the end of the path for java, put a semicolon (;), then the location of your python 2.7 install.

**Comment by johnpyp** [comment]
Yup, did that, now I'm getting this error: 
![image](https://cloud.githubusercontent.com/assets/20625636/17271984/ad788da6-5658-11e6-9b71-6a1358e661d0.png)

**Comment by noahc3** [comment]
Rerun install required modules. When you ran it last time, it installed for 3.5.1 not 2.7.11

**Comment by johnpyp** [comment]
Ah, ok, thanks.
